name: imprimir data

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  imprimir_datos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
        
      - name: instalar librerias
        run: |
            pip install pandas
            pip install matplotlib
            pip install detecta
            pip install peakutils

      - name: Run command in the vm
        run: |
          echo "tus datos son:"
          python graficador.py
          
